
# this is .traivs.yml written by -

# https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst
# https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst
# while this doesn't require sudo we don't want to run within a Docker container
sudo: true
dist: trusty
language: python
python:
  - "3.5"
env:
  global:
    - JOB_PATH=/tmp/devel_job
    - ABORT_ON_TEST_FAILURE=1
  matrix:
    - ROS_DISTRO_NAME=kinetic OS_NAME=ubuntu OS_CODE_NAME=xenial ARCH=amd64
    - ROS_DISTRO_NAME=melodic OS_NAME=ubuntu OS_CODE_NAME=bionic ARCH=amd64
    - ROS_DISTRO_NAME=noetic  OS_NAME=ubuntu OS_CODE_NAME=focal  ARCH=amd64
#   matrix:
#     allow_failures:
#       - env: ROS_DISTRO_NAME=kinetic OS_NAME=ubuntu OS_CODE_NAME=xenial ARCH=amd64
install:
  # check python code code compatibility
  - docker run --rm -v$(pwd):/opt/code -ti ${OS_NAME}:${OS_CODE_NAME} bash -c 'set -x; set -e; apt update -qq; apt install -y -qq lsb-release libroslib-dev python 2>&1 >/dev/null; set +x; for file in /etc/catkin/profile.d/*.sh; do echo $file; source $file; done; set -x; apt install -y -qq python${ROS_PYTHON_VERSION} 2>&1 >/dev/null; lsb_release -a; python${ROS_PYTHON_VERSION} --version; set +x; cd /opt/code; EXIT_STATUS=0; for file in $(find -type f); do if [[ $file == *.py || \"$(head -1 $file)\" =~ \"python\" ]]; then echo \"Check if $file is compatible with python${ROS_PYTHON_VERSION}\"; set -x; python${ROS_PYTHON_VERSION} -m py_compile $file || EXIT_STATUS=1; set +x; fi; done; exit $EXIT_STATUS';
  # either install the latest released version of ros_buildfarm
  - pip install ros_buildfarm
  # or checkout a specific branch
  #- git clone -b master https://github.com/ros-infrastructure/ros_buildfarm /tmp/ros_buildfarm
  #- pip install /tmp/ros_buildfarm
  # checkout catkin for catkin_test_results script
  - git clone https://github.com/ros/catkin /tmp/catkin
  # run devel job for a ROS repository with the same name as this repo
  - export REPOSITORY_NAME=`basename $TRAVIS_BUILD_DIR`
  # use the code already checked out by Travis
  - mkdir -p $JOB_PATH/ws/src
  - cp -R $TRAVIS_BUILD_DIR $JOB_PATH/ws/src/
  # generate the script to run a pre-release job for that target and repo
  - generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml $ROS_DISTRO_NAME default $OS_NAME $OS_CODE_NAME $ARCH  --output-dir $JOB_PATH
  # run the actual job which involves Docker
  - cd $JOB_PATH; sh ./prerelease.sh -y
script:
  # get summary of test results
  - /tmp/catkin/bin/catkin_test_results $JOB_PATH/ws/test_results --all
notifications:
  email: false

